name: "portal"
domain: "int.demo.ftcpro.co"
corsOrigins: "http://localhost:3000, https://*.demo.ftcpro.co, https://*.dev.demo.ftcpro.co, https://*.int.demo.ftcpro.co"
issuer: "letsencrypt-prod"
portContainer: 8080
portService: 8080
replicaCount: 1
securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true

portal:
  path: "/(.*)"
  name: "portal"
  image: "ftcpro.azurecr.io/frontend/product-portal-frontend:latest"

assets:
  path: "/((assets|swagger)/.*)"
  name: "assets"
  image: "ghcr.io/catenax-ng/product-portal-common-assets:main"

registration:
  path: "/registration/(.*)"
  name: "registration"
  image: "ftcpro.azurecr.io/frontend/product-portal-frontend-registration:latest"

demonstrator:
  path: "/demonstrator/(.*)"
  name: "demonstrator"
  image: "ghcr.io/catenax-ng/product-demonstrator:latest"
