domain: "dev.demo.ftcpro.co"

portal:
  image: "ftcpro.azurecr.io/frontend/product-portal-frontend:latest"

assets:
  image: "ghcr.io/catenax-ng/product-portal-common-assets:dev"

registration:
  image: "ftcpro.azurecr.io/frontend/product-portal-frontend-registration:latest"

demonstrator:
  image: "ghcr.io/catenax-ng/product-demonstrator:latest"
