name: portal-backend-pen
domain: dev.demo.ftcpro.co
corsOrigins: http://localhost:3000, https://*.dev.demo.ftcpro.co

postgresql:
  secret:
    pathinit: portal/data/pen/postgres
    pathinitdbuser: portal/data/pen/postgres-db-user

registration:
  image: ghcr.io/catenax-ng/product-portal-backend_registration-service:latest
  secret:
    path: portal/data/pen/registration

administration:
  image: ghcr.io/catenax-ng/product-portal-backend_administration-service:latest
  secret:
    path: portal/data/pen/administration

provisioning:
  image: ghcr.io/catenax-ng/product-portal-backend_provisioning-service:latest
  secret:
    path: portal/data/pen/provisioning

appmarketplace:
  image: ghcr.io/catenax-ng/product-portal-backend_marketplace-app-service:latest
  secret:
    path: portal/data/pen/appmarketplace

portalmigrations:
  image: ghcr.io/catenax-ng/product-portal-backend_portal-migrations:latest
  secret:
    path: portal/data/pen/portal-migrations

portalmaintenance:
  image: ghcr.io/catenax-ng/product-portal-backend_maintenance-service:latest
  secret:
    path: portal/data/pen/portal-maintenance

notification:
  image: ghcr.io/catenax-ng/product-portal-backend_notification-service:latest
  secret:
    path: portal/data/pen/notification

pgadmin4:
  enabled: true
  secret:
    path: portal/data/pen/pgadmin4
  env:
    email: portal@ftcpro.co
  existingSecret: secret-pgadmin4
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: portal-pgadmin4-pen.dev.demo.ftcpro.co
        paths:
        - path: /
          pathType: Prefix
    tls:
      - hosts:
        - portal-pgadmin4-pen.dev.demo.ftcpro.co
        secretName: portal-pgadmin4-pen.dev.demo.ftcpro.co-tls